# Generated by Django 5.1 on 2024-08-24 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadVecinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_actividad', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cupo_maximo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalacion', models.CharField(max_length=255)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('uso', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechaz', 'Rechazado')], default='pendiente', max_length=10)),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junta_vecinos.vecino')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoVecinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_postulacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechaz', 'Rechazado')], default='pendiente', max_length=10)),
                ('resolucion', models.TextField(blank=True, null=True)),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junta_vecinos.vecino')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('destinatarios', models.ManyToManyField(to='junta_vecinos.vecino')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junta_vecinos.actividadvecinal')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junta_vecinos.vecino')),
            ],
        ),
        migrations.CreateModel(
            name='CertificadoResidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('numero_certificado', models.CharField(max_length=20, unique=True)),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junta_vecinos.vecino')),
            ],
        ),
        migrations.AddField(
            model_name='actividadvecinal',
            name='inscritos',
            field=models.ManyToManyField(through='junta_vecinos.InscripcionActividad', to='junta_vecinos.vecino'),
        ),
    ]
