# Generated by Django 5.1 on 2024-08-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vecino',
            name='apellidos',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AddField(
            model_name='vecino',
            name='nombres',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
    ]
