# Generated by Django 5.1 on 2024-08-25 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0002_vecino_apellidos_vecino_nombres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('motivo', models.TextField()),
                ('foto_carnet_frente', models.ImageField(upload_to='carnets/')),
                ('foto_carnet_atras', models.ImageField(upload_to='carnets/')),
                ('documento_residencia', models.FileField(upload_to='documentos_residencia/')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CertificadoResidencia',
        ),
    ]
