# Generated by Django 5.1 on 2024-08-25 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0003_solicitudcertificado_delete_certificadoresidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoResidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificado', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='junta_vecinos.solicitudcertificado')),
            ],
        ),
    ]
