# Generated by Django 5.1 on 2024-10-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junta_vecinos', '0008_alter_proyectovecinal_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectovecinal',
            name='razon_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
